---
title: "Census vs LFS shares"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
#libraries-----------------------
library(tidyverse)
library(here)
library(conflicted)
library(vroom)
library(janitor)
library(readxl)
library(viridis)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::lag)
get_shares <- function(tbbl, group_var1, group_var2 = NULL) {
  tbbl|>
    group_by({{  group_var1  }}, {{  group_var2  }})|>
    summarize(across(c(census_share, lfs_share), ~sum(.x, na.rm = TRUE)))
}
compare_plot <- function(tbbl, accuracy, size, id1, id2=NULL) {
  plt <- tbbl|>
    mutate(distance=abs(census_share-lfs_share)/(census_share+lfs_share))|>
             ggplot(aes(x=census_share,
                   y=lfs_share,
                   text=paste0({{  id1  }}, " ", {{  id2  }}, "<br>",
                               "Census Share: ",
                                scales::percent(census_share, accuracy=accuracy), "<br>",
                                "LFS Share: ",
                                scales::percent(lfs_share, accuracy=accuracy))))+
  geom_abline(slope=1, intercept=0, linewidth=2, color="white") +
  geom_point(aes(fill = distance), shape = 21, size = size, color = "black", stroke = .1, show.legend=FALSE) +  
  labs(x="Census Share",
       y="LFS Share")+
  scale_x_continuous(trans="log10", labels=scales::percent) +
  scale_y_continuous(trans="log10", labels=scales::percent)+
  scale_fill_viridis_c(trans = "log")

plotly::ggplotly(plt, tooltip = "text")
}
```


```{r cache=TRUE}
census_mapping <- read_excel(here("data","mapping","mapping_census_to_lmo_63.xlsx"))
lfs_mapping <- read_excel(here("data", "mapping", "industry_mapping_2025_with_stokes_agg.xlsx"))|>
  select(naics_5, lmo_detailed_industry, lmo_ind_code)
industry_names <- lfs_mapping|>
  select(lmo_ind_code, lmo_detailed_industry)|>
  distinct()
lmo_nocs <-read_csv(here("data", "mapping", "noc21descriptions.csv"))|>
  select(lmo_noc, class_title)|>
  distinct()|>
  mutate(lmo_noc=as.character(lmo_noc),
         lmo_noc=str_pad(lmo_noc, "0", side = "left", width=5))|>
  rename(noc_5=lmo_noc)

census_shares <- tibble(files=list.files(here("data","census")))|>
  mutate(paths=here("data","census", files),
         data=map(paths, vroom))|>
  separate(files, into = c("bc_region", "extension"), sep = "\\.")|>
  select(bc_region, data)|>
  mutate(bc_region=if_else(bc_region=="North Coast", "North Coast & Nechako", bc_region),
         bc_region=if_else(bc_region=="Nechako", "North Coast & Nechako", bc_region)
  )|>
  unnest(data)|>
  group_by(bc_region, noc_5=`NOC (821)`)|>
  summarize(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)))|>
  pivot_longer(cols=-c(bc_region, noc_5),
               names_to = "census_column_heading",
               values_to = "employment")|>
  mutate(noc_5 = word(noc_5, 1))|>
  filter(employment>0,
         str_length(noc_5) == 5,
         noc_5!="Total"
  )|>
  inner_join(census_mapping)|>
  group_by(bc_region, lmo_ind_code, noc_5)|>
  summarize(employment=sum(employment, na.rm = TRUE))|>
  ungroup()|>
  mutate(census_share=employment/sum(employment, na.rm = TRUE))|>
  select(-employment)

lfs_shares <- vroom(list.files(here("data","status"), pattern = "_stat2125", full.names = TRUE))|>
  clean_names()|>
  rename(year=syear,
         employment=count)|>
  mutate(noc_5=if_else(noc_5 %in% c("00011", "00012", "00013", "00014", "00015"), "00018", noc_5))|>
  filter(year %in% 2021)|>
  na.omit()|>
  inner_join(lfs_mapping)|>
  group_by(bc_region, noc_5, lmo_ind_code, lmo_detailed_industry)|>
  summarize(employment=sum(employment))|>
  filter(employment>0)|>
  ungroup()|>
  mutate(lfs_share=employment/sum(employment, na.rm = TRUE))|>
  select(-employment)

shares <- full_join(lfs_shares, census_shares)|>
  mutate(across(where(is.numeric), ~replace_na(.x, 0)))|>
  left_join(lmo_nocs)

region_shares <- get_shares(shares, bc_region)
industry_shares <- get_shares(shares,lmo_ind_code)|>
  left_join(industry_names, by = "lmo_ind_code")
occupation_shares <- get_shares(shares, noc_5, class_title) 
```

Column 
-----------------------------------------------------------------------

### By Region

```{r}
 compare_plot(region_shares, .1, 3, bc_region)
```

Column 
-----------------------------------------------------------------------

### By Industry

```{r}
compare_plot(industry_shares, .01, 2, lmo_ind_code, lmo_detailed_industry)
```

Column 
-----------------------------------------------------------------------

### By Occupation

```{r}
compare_plot(occupation_shares, .001, 1, noc_5, class_title)
```

